### ISSUE TITLE
Flaky end-to-end tests/timing issues

### ISSUE THREAD

**Issue by textbook** [pivotal/postfacto#162]
While trying to upgrade the Node deps that cause audit warnings (`foundation-sites`, `react-scripts`\* and `serve`), I hit some issues with what seem to be timings in the E2E tests, e.g.:

```
  1) Felicity Journey
     Failure/Error: expect(page).to have_content('The board will be cleared ready for your next retro and incomplete action items will be carried across.')
       expected to find text "The board will be cleared ready for your next retro and incomplete action items will be carried across." in "My Retro\nMENU\n0\nthis is the first item\n0\nYour team can add happy, meh or sad items to these columns. Why don't you try adding one now?\n0\nSelect an item to start a discussion. You\u2019ll notice a 5 minute timer, so be sure to keep the conversation on track.\n0\nWhen you've addressed the item, mark it as \"Done\".\n0\nthis is the last item\n0\nHave you addressed all retro items?\n0\nIf so, it's time to archive the board. You\u2019ll find the Archive button in the menu.\nAction items\nToday (July 19)\nAdd action items with a single owner (Owner\u2019s Name)\nTick off action items when complete (Owner's Name)\nOlder\nContact Us\nTerms & Conditions\nPrivacy Policy"
```

Adding a sleep seemed to improve things, which is why I thought it was a timing problem, but putting in explicit sleeps is a bit of an anti-pattern; we want to avoid things like this:

```ruby
  def mark_all_retro_items_as_done
    sleep(0.3)
    find_all('div.retro-item').each do |retro_item|
      retro_item.click
      sleep(0.3)
      retro_item.find('.item-done').click
    end
  end
```

This is a tracking issue to give a place to report flaky tests (as Travis doesn't seem to give access to old builds when you restart them, so we need to copy those failures somewhere else) and figure out what and where needs improving.

\* *since upgraded in #161*

**Comment by textbook** [comment]
Currently failing for me locally in the Docker container:

```
Failures:

  1) Felicity Journey
     Failure/Error: retro_item.find('.item-done').click

     Capybara::ElementNotFound:
       Unable to find css ".item-done" within #<Capybara::Node::Element tag="div" path="/HTML/BODY[1]/DIV[1]/DIV[1]/DIV[1]/DIV[1]/SPAN[1]/DIV[1]/DIV[2]/DIV[1]/DIV[4]">
     # ./spec/spec_helper.rb:186:in `block in mark_all_retro_items_as_done'
     # ./spec/spec_helper.rb:183:in `mark_all_retro_items_as_done'
     # ./spec/felicity_journey_spec.rb:299:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:213:in `block (2 levels) in <top (required)>'
```

**Comment by textbook** [comment]
Failure in Travis for `textbook:upgrade-web-deps`
```
Failures:
  1) Felicity Journey
     Failure/Error: expect(page).to have_css('div.retro-item.discussed .item-text', text: 'this is a happy item')
       expected to find css "div.retro-item.discussed .item-text" but there were no matches
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-support-3.8.0/lib/rspec/support.rb:97:in `block in <module:Support>'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-support-3.8.0/lib/rspec/support.rb:106:in `notify_failure'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/expectations/handler.rb:40:in `handle_failure'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./spec/felicity_journey_spec.rb:416:in `block (2 levels) in <top (required)>'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `instance_exec'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `block in run'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `block in run'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:604:in `block in run_around_example_hooks_for'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:342:in `call'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:123:in `block in run'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `loop'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `run'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-retry-0.6.1/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./spec/spec_helper.rb:213:in `block (2 levels) in <top (required)>'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:373:in `execute_with'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:606:in `block (2 levels) in run_around_example_hooks_for'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:342:in `call'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:123:in `block in run'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `loop'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `run'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-retry-0.6.1/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:373:in `execute_with'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:606:in `block (2 levels) in run_around_example_hooks_for'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:342:in `call'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:607:in `run_around_example_hooks_for'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `run'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:251:in `run'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:629:in `block in run_examples'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:625:in `map'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:625:in `run_examples'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:591:in `run'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block (3 levels) in run_specs'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `map'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block (2 levels) in run_specs'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1989:in `with_suite_hooks'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:111:in `block in run_specs'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:74:in `report'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:110:in `run_specs'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:87:in `run'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in `run'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in `invoke'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/exe/rspec:4:in `<top (required)>'
     # /root/.rbenv/versions/2.6.3/bin/rspec:23:in `load'
     # /root/.rbenv/versions/2.6.3/bin/rspec:23:in `<top (required)>'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
     # /root/.rbenv/versions/2.6.3/bin/bundle:23:in `load'
     # /root/.rbenv/versions/2.6.3/bin/bundle:23:in `<main>'
```

**Comment by textbook** [comment]
Back to the archive issue after setting the global timeout to 20 seconds:

```
Failures:
  1) Felicity Journey
     Failure/Error: expect(page).to have_content('The board will be cleared ready for your next retro and incomplete action items will be carried across.')
       expected to find text "The board will be cleared ready for your next retro and incomplete action items will be carried across." in "My Retro\nMENU\n0\nthis is the first item\n0\nYour team can add happy, meh or sad items to these columns. Why don't you try adding one now?\n0\nSelect an item to start a discussion. You\u2019ll notice a 5 minute timer, so be sure to keep the conversation on track.\n0\nWhen you've addressed the item, mark it as \"Done\".\n0\nthis is the last item\n0\nHave you addressed all retro items?\n0\nIf so, it's time to archive the board. You\u2019ll find the Archive button in the menu.\nAction items\nToday (July 23)\nAdd action items with a single owner (Owner\u2019s Name)\nTick off action items when complete (Owner's Name)\nOlder\nContact Us\nTerms & Conditions\nPrivacy Policy"
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-support-3.8.0/lib/rspec/support.rb:97:in `block in <module:Support>'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-support-3.8.0/lib/rspec/support.rb:106:in `notify_failure'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/expectations/handler.rb:40:in `handle_failure'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./spec/felicity_journey_spec.rb:301:in `block (2 levels) in <top (required)>'
```

**Comment by textbook** [comment]
The issue with `expect(page).to have_css('div.retro-item.discussed .item-text', text: 'this is a happy item')` seemed to be a timing problem; adding a sleep between activating and retro item and attempting to click Done seemed to make it much more stable. The archive issue still seems to occur at a low frequency.

**Comment by textbook** [comment]
The same failure as above but, controversially, _not_ in Felicity's journey just came up in CI.

```
Failures:
  1) A Journey Of Two Participants Changing retro password and re-login for Peter
     Failure/Error: expect(page).to have_content 'The owner of this retro has chosen to protect it with a password.'
       expected to find text "The owner of this retro has chosen to protect it with a password." in "My Retro\nMENU\n0\nYour team can add happy, meh or sad items to these columns. Why don't you try adding one now?\n0\nSelect an item to start a discussion. You\u2019ll notice a 5 minute timer, so be sure to keep the conversation on track.\n0\nWhen you've addressed the item, mark it as \"Done\".\n0\nHave you addressed all retro items?\n0\nIf so, it's time to archive the board. You\u2019ll find the Archive button in the menu.\nAction items\nToday (October 25)\nAdd action items with a single owner (Owner\u2019s Name)\nTick off action items when complete (Owner's Name)\nOlder\nContact Us\nTerms & Conditions\nPrivacy Policy"
     # ./spec/a_journey_of_two_participants_journey_spec.rb:372:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:194:in `in_browser'
     # ./spec/a_journey_of_two_participants_journey_spec.rb:370:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:213:in `block (2 levels) in <top (required)>'
```

**Comment by j-lea** [comment]
We have done some digging and think it is because the archive model isn't appearing, because not all of the issues are marked as done. 

**When the test passes** - the modal shows and all retro items have the `discussed` class. 
![Screenshot 2020-05-06 at 09 19 03](https://user-images.githubusercontent.com/45389321/81154966-5a2f7e00-8f7c-11ea-9804-c445d3ca4667.png)

**When the test fails** - no modal and one of the retro items does not have the `discussed` class, so it makes sense that the criteria to show the modal hasn't been met. 
![Screenshot 2020-05-06 at 09 19 48](https://user-images.githubusercontent.com/45389321/81155144-8c40e000-8f7c-11ea-8646-a7f5a6ccae59.png)

Whats weird is that the problem *seems* to always be with `#retro-item-3`?
