### ISSUE TITLE
LoadError: cannot load such file -- coffee_script

### ISSUE THREAD

**Issue by textbook** [pivotal/postfacto#183]
When using the `test-package.sh` script with the latest non-release version, 873ed78, I see the following error when *upgrading* the app on Heroku (the fresh deploy works fine):

```
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        I, [2019-08-15T17:04:55.399664 #1139]  INFO -- : Writing /tmp/build_024de83a6f8125c3be657663273ec2f0/public/assets/archived_email-73a7fe22b98aba002a1d142ed52825d7ad8a81e1975d1d2370dcb1849a994999.css
remote:        I, [2019-08-15T17:04:55.400270 #1139]  INFO -- : Writing /tmp/build_024de83a6f8125c3be657663273ec2f0/public/assets/archived_email-73a7fe22b98aba002a1d142ed52825d7ad8a81e1975d1d2370dcb1849a994999.css.gz
remote:        I, [2019-08-15T17:04:55.536234 #1139]  INFO -- : Writing /tmp/build_024de83a6f8125c3be657663273ec2f0/public/assets/active_admin-4bb70b3d291d81707bc3a21523f31c065aeca8f7821f0a62e50fc2fb13b8df4d.css
remote:        I, [2019-08-15T17:04:55.536415 #1139]  INFO -- : Writing /tmp/build_024de83a6f8125c3be657663273ec2f0/public/assets/active_admin-4bb70b3d291d81707bc3a21523f31c065aeca8f7821f0a62e50fc2fb13b8df4d.css.gz
remote:        I, [2019-08-15T17:04:55.559705 #1139]  INFO -- : Writing /tmp/build_024de83a6f8125c3be657663273ec2f0/public/assets/active_admin/print-cf99cbf27fb92065a9eacd28e6fad48fa72cadaf6e0918790e8d35b11d8f99f6.css
remote:        I, [2019-08-15T17:04:55.559839 #1139]  INFO -- : Writing /tmp/build_024de83a6f8125c3be657663273ec2f0/public/assets/active_admin/print-cf99cbf27fb92065a9eacd28e6fad48fa72cadaf6e0918790e8d35b11d8f99f6.css.gz
remote:        rake aborted!
remote:        LoadError: cannot load such file -- coffee_script
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/autoload/coffee_script.rb:1:in `<top (required)>'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/coffee_script_processor.rb:15:in `cache_key'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:93:in `processor_cache_key'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:22:in `block in initialize'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:53:in `processor_cache_key'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:102:in `block in processors_cache_keys'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:102:in `map'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:102:in `processors_cache_keys'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processing.rb:159:in `resolve_processors_cache_key_uri'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets.rb:162:in `block in <module:Sprockets>'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/dependencies.rb:67:in `resolve_dependency'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:23:in `block in initialize'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:59:in `resolve_dependency'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:268:in `block in resolve_dependencies'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:268:in `map'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:268:in `resolve_dependencies'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:55:in `block in load'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:311:in `block in fetch_asset_from_dependency_cache'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:307:in `each'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:307:in `each_with_index'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:307:in `fetch_asset_from_dependency_cache'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:134:in `block in find'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `each'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `find'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
remote:        /tmp/build_024de83a6f8125c3be657663273ec2f0/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
remote:        Tasks: TOP => assets:precompile
remote:        (See full trace by running task with --trace)
remote: 
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !       Push rejected to postfacto-old-api-1565888327.
remote: 
To https://git.heroku.com/postfacto-old-api-1565888327.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/postfacto-old-api-1565888327.git'
```

It seems that there is state from the previous deployment of the application. I've tried adding the following to `upgrade-heroku.sh` to clean out any cached assets that may still require CoffeeScript, but to no avail:

```bash
heroku run rake tmp:cache:clear -a ${API_HOST} -x
```

Note that the deploy and upgrade both work fine on Cloud Foundry, presumably as they're building a completely fresh droplet every time, so this is something specifically related to the way Heroku deals with apps.

**Comment by textbook** [comment]
Closed by #174
