### ISSUE TITLE
MySQL secure connection problems: Deploying on TAS

### ISSUE THREAD

**Issue by sumitAtDigital** [pivotal/postfacto#300]
Hi Guys,

We are getting connection problems while deploying postfacto app on TAS. 
Hope you might be aware of this issue already. Please suggest.

_2020-07-28T13:22:35.109+02:00 [APP/PROC/WEB/0] [ERR] Mysql2::Error: Connections using insecure transport are prohibited while --require_secure_transport=ON.
2020-07-28T13:22:22.837+02:00 [APP/PROC/WEB/1] [ERR] /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `connect'_

Thanks,
Sumit

**Comment by butzopower** [comment]
Hi Sumit, thanks for using Postfacto!

This looks like an issue coming from the MySQL server not allowing non-SSL connections.  The Postfacto code shouldn't actually be doing anything special to manage the connection, and it should be up to the ruby-buildpack on TAS to configure the application properly with credentials and forward them on.

Two questions that might help:
- How did you deploy Postfacto on to your TAS? 
- How is the database currently being configured for your Postfacto on TAS?

**Comment by jmichelgarcia** [comment]
Hi @sumitAtDigital 👋,

Might be helpful to post an anonymised output of the VCAP_SERVICES the app is receiving. Cheers

**Comment by sumitAtDigital** [comment]
Hi Michael and Brian,

Thanks for your reply!

Just deployed in another test TAS foundation which uses _useSSL=false_, and it's working well.
However, at more secured platform where we use TLS and keep _useSSL=true&requireSSL=true&serverSslCert=xxxxx/yyyy/zzzz"_ it's not working. 
_**Error**_: Mysql2::Error: Connections using insecure transport are prohibited while --require_secure_transport=ON.

This is the only difference in VCAP_SERVICES.

Hope this will give some idea.

Thanks,
Sumit

**Comment by jmichelgarcia** [comment]
Thank you @sumitAtDigital!
Could you nevertheless post the whole of your VCAP_SERVICES? 

VCAP_SERVICES looks like this, and you should be able to get it by typing `cf env <postfacto-app-name>`

```
VCAP_SERVICES =
{
  "postgresql-10-odb": [
    {
      "name": "postgresql-10-odb-c6c60",
      "label": "postgresql-10-odb",
      "credentials": {
        "uri": "postgres://exampleuser:examplepass@babar.postgresql-10-odb.com:5432/exampledb"
      }
    }
  ]
}
```

Cheers!

**Comment by sumitAtDigital** [comment]
Hi @jmichelgarcia
Please see env vars as asked:

 "VCAP_SERVICES": {
  "p-redis": [
   {
    "binding_name": null,
    "credentials": {
     "host": "xx.xxx.xxx.xxx",
     "password": "xxxxx-xxx-xxxx-xxxx-pqdxxxxbxxxx",
     "port": 35015
    },
    "instance_name": "postfacto-redis",
    "label": "p-redis",
    "name": "postfacto-redis",
    "plan": "shared-vm",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "pivotal",
     "redis"
    ],
    "volume_mounts": []
   }
  ],
  "p.mysql": [
   {
    "binding_name": null,
    "credentials": {
     "credhub-ref": "/c/xxxx-xxxx-xxxx-xxxx-xxxx/xxxxx-xxxxx-xxxx-a121-xxxxxx/xxxxxx-klmn-xxxx-xxxx-xxxxxxxxx/credentials"
    },
    "instance_name": "postfacto-db",
    "label": "p.mysql",
    "name": "postfacto-db",
    "plan": "db-backup-single-node",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "mysql"
    ],
    "volume_mounts": []
   }
  ]
 }
}

Thanks,
Sumit

**Comment by sureshgoli25** [comment]
Hi,

I also have similar problem with secure connections.

Our setup is `VMWare Tanzu 2.9 + MySQL for VMWare 2.8.1 and Redis 2.3.3`

MySQL for VMWare Tanzu is configured to allow secure Connections, refence URL is `https://docs.pivotal.io/p-mysql/2-8/install-config.html#security`

Any help would be highly appreicated.

**Comment by jmichelgarcia** [comment]
I was able to reproduce this on a fresh PAS install and the Secure Only option for MySQL on, the full stack trace is:

 ```
2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR rake aborted!
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR Mysql2::Error: Connections using insecure transport are prohibited while --require_secure_transport=ON.
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `connect'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `initialize'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_handling.rb:189:in `connection'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <top (required)>'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/railties/databases.rake:84:in `each'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <top (required)>'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
   2020-08-01T10:18:29.83+0100 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `ex
```

**Comment by jmichelgarcia** [comment]
@sumitAtDigital, @sureshgoli25,

As a workaround, could you try adding the below code snipped to the `package/assets/config/database.yml` file and re-executing  ./deploy.sh postfacto from the `package/tas/` directory?

```yaml
production:
  sslmode: preferred
  sslca: /etc/ssl/certs/ca-certificates.crt
```

Let me know if that works.

**Comment by sumitAtDigital** [comment]
Thanks @jmichelgarcia !

It's working now.
