### ISSUE TITLE
Deploying fails when Redis is not password protected

### ISSUE THREAD

**Issue by tenjaa** [Pivotal/postfacto#73]
Hey,

I am trying to get Postfacto running in our own CloudFoundry instance.
Unfortunately I get an error while deploying the api and I do not really know where to look.
Can you help me?

The buildpack is running in version 1.7.19 and cannot be changed by me.
Postfacto is version 2.4.1.

```
C:\Users\xxUserxx\Downloads\postfacto-2.4.1\package\pcf>cf push -f config/manifest-api.yml -p assets/api
Using manifest file config/manifest-api.yml

Updating app postfacto-api in org MYORG / space development as xxEmailxx...
OK

Uploading postfacto-api...
Uploading app files from: C:\Users\xxUserxx\Downloads\postfacto-2.4.1\package\pcf\assets\api
Uploading 151.6K, 213 files
Done uploading
OK
Binding service postfacto-db to app postfacto-api in org MYORG / space development as xxEmailxx...
OK
Binding service postfacto-redis to app postfacto-api in org MYORG / space development as xxEmailxx...
OK

Starting app postfacto-api in org MYORG / space development as xxEmailxx...
Downloading dotnet_core_buildpack_cached...
Downloading java_buildpack...
Downloading go_buildpack...
Downloading ruby_buildpack...
Downloading staticfile_buildpack...
Downloaded go_buildpack
Downloading nodejs_buildpack...
Downloaded ruby_buildpack
Downloading ruby_buildpack_cached...
Downloaded java_buildpack
Downloading python_buildpack...
Downloaded staticfile_buildpack
Downloading python_buildpack_cached...
Downloaded nodejs_buildpack
Downloading php_buildpack...
Downloaded dotnet_core_buildpack_cached
Downloading nodejs_buildpack_cached...
Downloaded ruby_buildpack_cached
Downloading go_buildpack_cached...
Downloaded php_buildpack
Downloading binary_buildpack...
Downloaded python_buildpack
Downloading staticfile_buildpack_cached...
Downloaded python_buildpack_cached
Downloading java_buildpack_cached...
Downloaded nodejs_buildpack_cached
Downloading dotnet_core_buildpack...
Downloaded binary_buildpack
Downloading php_buildpack_cached...
Downloaded go_buildpack_cached
Downloading binary_buildpack_cached...
Downloaded java_buildpack_cached
Downloaded dotnet_core_buildpack
Downloaded staticfile_buildpack_cached
Downloaded php_buildpack_cached
Downloaded binary_buildpack_cached
Cell adf200ee-e782-4eb8-bb34-96194a83b358 creating container for instance 8f2e4aa2-d598-4596-b5cc-970a400c7f94
Cell adf200ee-e782-4eb8-bb34-96194a83b358 successfully created container for instance 8f2e4aa2-d598-4596-b5cc-970a400c7f94
Downloading app package...
Downloaded app package (142.5K)
-----> Ruby Buildpack version 1.7.19
-----> Supplying Ruby
-----> Installing bundler 1.16.2
       Download [https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler-1.16.2-8cdae990.tgz]
-----> Installing ruby 2.4.4
       Download [https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.4.4-linux-x64-8e992e9b.tgz]
-----> Update rubygems from 2.6.14.1 to 2.7.7
-----> Installing rubygems 2.7.7
       Download [https://buildpacks.cloudfoundry.org/dependencies/rubygems/rubygems-2.7.7-4cb2c9a3.tgz]
-----> Installing node 6.14.2
       Download [https://buildpacks.cloudfoundry.org/dependencies/node/node-6.14.2-linux-x64-345ad39f.tgz]
-----> Installing dependencies using bundler 1.16.2
       Running: bundle install --without development:test --jobs=4 --retry=4 --path /tmp/contents914288057/deps/0/vendor_bundle --binstubs /tmp/contents914288057/deps/0/binstubs --deployment
       Fetching gem metadata from https://rubygems.org/.......
       Fetching rake 12.3.1
       Fetching concurrent-ruby 1.0.5
       Fetching minitest 5.11.3
       Installing minitest 5.11.3
       Installing rake 12.3.1
       Installing concurrent-ruby 1.0.5
       Fetching thread_safe 0.3.6
       Fetching builder 3.2.3
       Installing thread_safe 0.3.6
       Fetching erubi 1.7.1
       Installing builder 3.2.3
       Fetching mini_portile2 2.3.0
       Fetching crass 1.0.4
       Installing erubi 1.7.1
       Fetching rack 2.0.5
       Installing mini_portile2 2.3.0
       Fetching nio4r 2.3.1
       Installing crass 1.0.4
       Installing rack 2.0.5
       Fetching websocket-extensions 0.1.3
       Installing nio4r 2.3.1 with native extensions
       Installing websocket-extensions 0.1.3
       Fetching mini_mime 1.0.0
       Installing mini_mime 1.0.0
       Fetching coffee-script-source 1.12.2
       Fetching execjs 2.7.0
       Installing execjs 2.7.0
       Installing coffee-script-source 1.12.2
       Fetching method_source 0.8.2
       Fetching thor 0.20.0
       Installing method_source 0.8.2
       Fetching formtastic_i18n 0.6.0
       Installing thor 0.20.0
       Fetching kaminari-core 1.1.1
       Installing formtastic_i18n 0.6.0
       Fetching arel 8.0.0
       Installing kaminari-core 1.1.1
       Fetching rb-fsevent 0.10.3
       Installing arel 8.0.0
       Fetching ffi 1.9.23
       Installing rb-fsevent 0.10.3
       Fetching public_suffix 3.0.0
       Installing public_suffix 3.0.0
       Fetching bcrypt 3.1.11
       Installing ffi 1.9.23 with native extensions
       Installing bcrypt 3.1.11 with native extensions
       Using bundler 1.16.2
       Fetching cf-app-utils 0.6
       Installing cf-app-utils 0.6
       Fetching orm_adapter 0.5.0
       Installing orm_adapter 0.5.0
       Fetching unf_ext 0.0.7.4
       Installing unf_ext 0.0.7.4 with native extensions
       Fetching htmlentities 4.3.4
       Installing htmlentities 4.3.4
       Fetching multi_json 1.12.2
       Installing multi_json 1.12.2
       Fetching mime-types-data 3.2016.0521
       Installing mime-types-data 3.2016.0521
       Fetching mysql2 0.4.9
       Installing mysql2 0.4.9 with native extensions
       Fetching netrc 0.11.0
       Installing netrc 0.11.0
       Fetching pg 0.21.0
       Installing pg 0.21.0 with native extensions
       Fetching puma 3.10.0
       Installing puma 3.10.0 with native extensions
       Fetching rack-cors 1.0.1
       Installing rack-cors 1.0.1
       Fetching redis 3.3.3
       Installing redis 3.3.3
       Fetching i18n 1.0.1
       Installing i18n 1.0.1
       Fetching tzinfo 1.2.5
       Installing tzinfo 1.2.5
       Fetching nokogiri 1.8.4
       Installing nokogiri 1.8.4 with native extensions
       Fetching websocket-driver 0.6.5
       Installing websocket-driver 0.6.5 with native extensions
       Fetching mail 2.7.0
       Installing mail 2.7.0
       Fetching rack-test 1.0.0
       Installing rack-test 1.0.0
       Fetching sprockets 3.7.2
       Installing sprockets 3.7.2
       Fetching warden 1.2.7
       Installing warden 1.2.7
       Fetching uglifier 3.2.0
       Installing uglifier 3.2.0
       Fetching coffee-script 2.4.1
       Installing coffee-script 2.4.1
       Fetching addressable 2.5.2
       Installing addressable 2.5.2
       Fetching mime-types 3.1
       Installing mime-types 3.1
       Fetching rb-inotify 0.9.10
       Installing rb-inotify 0.9.10
       Fetching unf 0.1.4
       Installing unf 0.1.4
       Fetching activesupport 5.1.6
       Installing activesupport 5.1.6
       Fetching css_parser 1.6.0
       Installing css_parser 1.6.0
       Fetching sass-listen 4.0.0
       Installing sass-listen 4.0.0
       Fetching domain_name 0.5.20170404
       Installing domain_name 0.5.20170404
       Fetching globalid 0.4.1
       Installing globalid 0.4.1
       Fetching arbre 1.1.1
       Installing arbre 1.1.1
       Fetching activemodel 5.1.6
       Installing activemodel 5.1.6
       Fetching jbuilder 2.7.0
       Installing jbuilder 2.7.0
       Fetching premailer 1.10.4
       Installing premailer 1.10.4
       Fetching sass 3.5.5
       Installing sass 3.5.5
       Fetching http-cookie 1.0.3
       Installing http-cookie 1.0.3
       Installing activejob 5.1.6
       Fetching activejob 5.1.6
       Fetching activerecord 5.1.6
       Installing activerecord 5.1.6
       Fetching rest-client 2.0.2
       Installing rest-client 2.0.2
       Fetching kaminari-activerecord 1.1.1
       Installing kaminari-activerecord 1.1.1
       Fetching polyamorous 1.3.3
       Installing polyamorous 1.3.3
       Fetching friendly_id 5.1.0
       Installing friendly_id 5.1.0
       Fetching rails-dom-testing 2.0.3
       Fetching loofah 2.2.2
       Installing rails-dom-testing 2.0.3
       Installing loofah 2.2.2
       Fetching rails-html-sanitizer 1.0.4
       Installing rails-html-sanitizer 1.0.4
       Fetching actionview 5.1.6
       Installing actionview 5.1.6
       Fetching actionpack 5.1.6
       Fetching kaminari-actionview 1.1.1
       Installing kaminari-actionview 1.1.1
       Fetching kaminari 1.1.1
       Installing actionpack 5.1.6
       Installing kaminari 1.1.1
       Fetching actioncable 5.1.6
       Fetching actionmailer 5.1.6
       Fetching railties 5.1.6
       Installing actionmailer 5.1.6
       Installing actioncable 5.1.6
       Fetching formtastic 3.1.5
       Fetching has_scope 0.7.1
       Installing railties 5.1.6
       Installing has_scope 0.7.1
       Fetching ransack 1.8.7
       Installing formtastic 3.1.5
       Installing ransack 1.8.7
       Fetching sprockets-rails 3.2.1
       Fetching premailer-rails 1.9.7
       Fetching coffee-rails 4.2.2
       Installing coffee-rails 4.2.2
       Installing sprockets-rails 3.2.1
       Installing premailer-rails 1.9.7
       Fetching responders 2.4.0
       Fetching jquery-rails 4.3.1
       Fetching rails 5.1.6
       Installing responders 2.4.0
       Fetching inherited_resources 1.8.0
       Installing rails 5.1.6
       Fetching devise 4.3.0
       Installing inherited_resources 1.8.0
       Installing jquery-rails 4.3.1
       Installing devise 4.3.0
       Fetching activeadmin 1.2.1
       Installing activeadmin 1.2.1
       Bundle complete! 29 Gemfile dependencies, 89 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into `/tmp/contents914288057/deps/0/vendor_bundle`
-----> Regenerating bundler binstubs...
       Cleaning up the bundler cache.
-----> Creating runtime environment
-----> Saving vendor_bundle to cache
-----> Finalizing Ruby
-----> Precompiling assets
       rake aborted!
       KeyError: key not found: "password"
       (erb):39:in `fetch'
       (erb):39:in `<main>'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/application.rb:233:in `config_for'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/actioncable-5.1.6/lib/action_cable/engine.rb:31:in `block (2 levels) in <class:Engine>'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:69:in `instance_eval'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:49:in `each'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/actioncable-5.1.6/lib/action_cable/server/base.rb:85:in `<module:Server>'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/actioncable-5.1.6/lib/action_cable/server/base.rb:4:in `<module:ActionCable>'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/actioncable-5.1.6/lib/action_cable/server/base.rb:3:in `<top (required)>'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/actioncable-5.1.6/lib/action_cable.rb:44:in `server'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/actioncable-5.1.6/lib/action_cable/engine.rb:46:in `block (3 levels) in <class:Engine>'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:436:in `instance_exec'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:436:in `eval_block'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:453:in `block in clear!'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:453:in `each'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:453:in `clear!'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/application/routes_reloader.rb:50:in `block in clear!'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/application/routes_reloader.rb:48:in `each'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/application/routes_reloader.rb:48:in `clear!'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/application/routes_reloader.rb:17:in `reload!'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/application/routes_reloader.rb:41:in `block in updater'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/file_update_checker.rb:81:in `execute'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/application/routes_reloader.rb:42:in `updater'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/application/routes_reloader.rb:31:in `execute_if_updated'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/application/finisher.rb:128:in `block in <module:Finisher>'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `run'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/initializable.rb:59:in `block in run_initializers'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/initializable.rb:58:in `run_initializers'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/application.rb:353:in `initialize!'
       /tmp/app/config/environment.rb:35:in `<top (required)>'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/application.rb:329:in `require_environment!'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/application.rb:445:in `block in run_tasks_blocks'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
       /tmp/contents914288057/deps/0/vendor_bundle/ruby/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
       /tmp/contents914288057/deps/0/bin/bundle:104:in `load'
       /tmp/contents914288057/deps/0/bin/bundle:104:in `<main>'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
       Asset precompilation completed (2.228355213s)
       **ERROR** Error precompiling assets: exit status 1
Failed to compile droplet: Failed to run finalize script: exit status 12
Exit status 223
Cell adf200ee-e782-4eb8-bb34-96194a83b358 stopping instance 8f2e4aa2-d598-4596-b5cc-970a400c7f94
Cell adf200ee-e782-4eb8-bb34-96194a83b358 destroying container for instance 8f2e4aa2-d598-4596-b5cc-970a400c7f94
Cell adf200ee-e782-4eb8-bb34-96194a83b358 successfully destroyed container for instance 8f2e4aa2-d598-4596-b5cc-970a400c7f94

FAILED
Error restarting application: BuildpackCompileFailed

TIP: use 'cf logs postfacto-api --recent' for more information
```

**Comment by seadowg** [comment]
First thought is that this could be happening during the websocket initialization in https://github.com/Pivotal/postfacto/blob/master/api/config/cable.yml#L39. You'll see it expects the redis service to include a 'password' key in it's credentials object (`c.fetch('password')`).

Are you able to post at the credentials (censored obviously) object for your `postfact-redis` service instance? You can output the whole env for your app by running `cf env postfacto-api`.

**Comment by tenjaa** [comment]
Yes this is it. The redis instance is not secured by some password but only by some ip whitelisting or similar (I hope 🙏)

```
Getting env variables for app postfacto-api in org MYORG / space development as email...
OK

System-Provided:
{
 "VCAP_SERVICES": {
  "aws_aurora": [
   {
    "binding_name": null,
    "credentials": {
     "ca_cert": "url",
     "endpoint": "something.com",
     "engine": "aurora",
     "hostname": "something.amazonaws.com",
     "instance_identifier": "xx-xx-xx-xx-xx",
     "jdbcUrl": "jdbc:user:pass@url:3306/something",
     "name": "db_xx_XX_XX",
     "password": "password",
     "port": 3306,
     "requires_tls": true,
     "uri": "mysql://user:pass@url:3306/something?reconnect=true",
     "username": "username"
    },
    "instance_name": "postfacto-db",
    "label": "aws_aurora",
    "name": "postfacto-db",
    "plan": "standard",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "aurora",
     "aws",
     "shared"
    ],
    "volume_mounts": []
   }
  ],
  "aws_elasticache": [
   {
    "binding_name": null,
    "credentials": {
     "host": "xxxxx.cache.amazonaws.com",
     "instance_identifier": "xxx-xxx-xx-xx-xx",
     "port": 6379
    },
    "instance_name": "postfacto-redis",
    "label": "aws_elasticache",
    "name": "postfacto-redis",
    "plan": "xx",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "redis",
     "aws",
     "nosql"
    ],
    "volume_mounts": []
   }
  ]
 }
}

{
 "VCAP_APPLICATION": {
  "application_id": "xx-xx-xx",
  "application_name": "postfacto-api",
  "application_uris": [
   "appuri"
  ],
  "application_version": "xx-xx-xx",
  "cf_api": "apiuri",
  "limits": {
   "disk": 1024,
   "fds": 16384,
   "mem": 256
  },
  "name": "postfacto-api",
  "space_id": "xx-xx-xx",
  "space_name": "development",
  "uris": [
   "apiuri"
  ],
  "users": null,
  "version": "xx-xx-xx"
 }
}

User-Provided:
CLIENT_ORIGIN: postfacto-uri
WEBSOCKET_PORT: 443

No running env variables have been set

Staging Environment Variable Groups:
JBP_CONFIG_CONTAINER_SECURITY_PROVIDER: { key_manager_enabled: false, trust_manager_enabled: true }
```

**Comment by tenjaa** [comment]
Simply removing `c.fetch('password')` solves the problem for me right now.
Next problem seems to be the connection to the database.
The username is the one from the env variables. But I do not know where the ip is coming from because in the env variables are only urls given. I even took another app via ssh to ping all urls I could find and none of them matches the ip given in the logs.

```
2018-07-21T07:48:36.41+0200 [CELL/0] OUT Starting health monitoring of container
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR rake aborted!
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR Mysql2::Error: Access denied for user 'username'@'someip' (using password: YES)
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:89:in `connect'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:89:in `initialize'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/mysql2_adapter.rb:21:in `new'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/mysql2_adapter.rb:21:in `mysql2_connection'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:759:in `new_connection'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:803:in `checkout_new_connection'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:782:in `try_to_checkout_new_connection'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:743:in `acquire_connection'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `retrieve_connection'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/connection_handling.rb:88:in `connection'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/schema_migration.rb:20:in `table_exists?'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/schema_migration.rb:24:in `create_table'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1125:in `initialize'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1007:in `new'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1007:in `up'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:985:in `migrate'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/bin/bundle:104:in `load'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR /home/vcap/deps/0/bin/bundle:104:in `<main>'
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR Tasks: TOP => db:migrate
   2018-07-21T07:48:39.03+0200 [APP/PROC/WEB/1] ERR (See full trace by running task with --trace)
   2018-07-21T07:48:39.05+0200 [APP/PROC/WEB/1] OUT Exit status 1
   2018-07-21T07:48:39.05+0200 [CELL/SSHD/1] OUT Exit status 0
```

**Comment by tenjaa** [comment]
Yes just works. I added the env output below, maybe it helps you but it is ok for now for us.
I'd prefer to use mysql because only our larger instances have postgresql available and they are just oversized for this usecase. But that should be a thing we could also solve on our side :)

And also yes, I just removed the `c.fetch('password')` so making it optional should help. I pasted the line how I have it below.

```
"aws_aurora": [
   {
    "binding_name": null,
    "credentials": {
     "ca_cert": "ca-url",
     "endpoint": "some.endpoint.amazonaws.com",
     "engine": "aurora-postgresql",
     "group": "postgresql group",
     "hostname": "some.hostname.amazonaws.com",
     "instance_identifier": "instance id",
     "jdbcUrl": "jdbc:postgresql://the.url.com/somepasswordsandusers\u0026ssl=true\u0026user=user",
     "name": "db_name",
     "password": "password",
     "port": 5432,
     "requires_tls": true,
     "uri": "postgres://some.endpoint.amazonaws.com:5432/instance-id?reconnect=true",
     "username": "user"
    },
    "instance_name": "postfacto-db",
    "label": "aws_aurora",
    "name": "postfacto-db",
    "plan": "standard",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "aurora",
     "aws",
     "shared"
    ],
    "volume_mounts": []
   }
  ],
```

`url: <%= ENV["RAILS_ENV"] == "production" && (c = CF::App::Credentials.find_by_service_tag('redis')) && Addressable::URI.new(scheme: 'redis', host: c["hostname"] || c.fetch('host'), port: c.fetch('port')).to_s %>`
