### ISSUE TITLE
`gulp local-acceptance` fails on master

### ISSUE THREAD

**Issue by mjstallard** [pivotal/postfacto#78]
Hello lovely Postfacto people! 👋 

I've been working on adding Heroku support for Postfacto. Before making a PR, I went to check that I hadn't broken anything in the local acceptance tests, but it looks like they're failing on master (at least on my machine). The failures seem to be consistently:

```
Failures:

  1) Felicity Auto facilitation journey
     Failure/Error: expect(page).to have_content('The board will be cleared ready for your next retro and incomplete action items will be carried across.')
       expected to find text "The board will be cleared ready for your next retro and incomplete action items will be carried across." in "By accessing and using Postfacto, you agree to our Terms of Use and Privacy Policy and use of cookies\nOK\nauto-facilitate-retro\nVIDEO\nMENU\n0\nsomething happy 1\n4\nsomething really happy\n0\nsomething meh 1\n0\nsomething sad 1\nAction items\nToday (September 12)\nOlder\nContact UsTerms & ConditionsPrivacy Policy"
     # ./spec/felicity_journey_spec.rb:287:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:207:in `block (2 levels) in <top (required)>'

  2) Felicity when they have registered before starting a retro can open video call
     Failure/Error: expect(page).to have_content("appear.in")
       expected to find text "appear.in" in "You're about to join a video meeting\nCam/mic not active\nAllow cam/mic\nYou can turn your video off any time inside the room". (However, it was found 16 times including non-visible text.)
     # ./spec/felicity_journey_spec.rb:146:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:207:in `block (2 levels) in <top (required)>'
```

Is this an actual problem/test flake, or am I just Doing It Wrong™?

**Comment by seadowg** [comment]
👋

Excited that you're working on a Heroku version!

Just saw the same failures on CI so I think these are legit. Maybe makes sense to submit a PR given the problems are unrelated.
